import { type NextPage } from "next";
import Head from "next/head";

import {
  Box,
  Grid,
  GridItem,
  Heading,
  Show,
  useMediaQuery,
} from "@chakra-ui/react";
import NavBar from "~/Components/NavBar";
import SideBar from "~/Components/SideBar";
import HamburgerMenu from "~/Components/HambugerMenu";
import React from "react";
import PieChart from "~/Components/PieChart";
import BarChart from "~/Components/BarChart";
import ActiveProjects from "~/Components/ActiveProjects";
import { SignedIn, SignedOut } from "@clerk/nextjs";

const Home: NextPage = () => {
  const [isMobile] = useMediaQuery("(max-width: 768px)");
  return (
    <>
      <Head>
        <title>TimeIt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          templateAreas={{
            base: `"nav nav" 
                   "hamburger main"`,
            lg: `"nav nav" 
                 "aside main"`,
          }}
          templateColumns={{ base: "1fr", lg: "200px 1fr" }}
        >
          <GridItem area="nav">
            <NavBar />
          </GridItem>
          <Show above="lg">
            <GridItem area="aside">
              <SideBar />
            </GridItem>
          </Show>
          <Show below="lg">
            <GridItem area="hamburger">
              <HamburgerMenu />
            </GridItem>
          </Show>
          <GridItem area="main">
            <SignedIn>
              <Grid
                templateAreas={{
                  base: `"project" "pie" "bar"`,
                  lg: `"project pie pie" "bar bar bar"`,
                }}
                gridAutoColumns="minmax(0, 1fr)"
                gap="50px"
                m={10}
              >
                <GridItem
                  area="project"
                  height="28rem"
                  bg="#D2DFF3"
                  borderRadius="15px"
                >
                  <Heading
                    textAlign="center"
                    fontFamily="Inter"
                    fontWeight="400"
                    fontSize="48px"
                  >
                    My projects
                  </Heading>
                  <ActiveProjects />
                </GridItem>
                <GridItem area="pie" bg="#D2DFF3" borderRadius="15px">
                  <Heading
                    textAlign="center"
                    fontFamily="Inter"
                    fontWeight="400"
                    fontSize="48px"
                  >
                    Top 5 projects
                  </Heading>
                  <Box height="28rem">
                    <PieChart hasLegends={!isMobile} />
                  </Box>
                </GridItem>
                <GridItem area="bar" bg="#D2DFF3" borderRadius="15px">
                  <Heading
                    textAlign="center"
                    fontFamily="Inter"
                    fontWeight="400"
                    fontSize="40px"
                  >
                    Hours worked
                  </Heading>
                  <Box height="28rem">
                    <BarChart layout={isMobile ? "horizontal" : "vertical"} />
                  </Box>
                </GridItem>
              </Grid>
            </SignedIn>
            <SignedOut>
              <Box>You must sign in</Box>
            </SignedOut>
          </GridItem>
        </Grid>
      </main>
    </>
  );
};

export default Home;
