import { type NextPage } from "next";
import Head from "next/head";

import { Accordion, Box, Grid, GridItem, Show } from "@chakra-ui/react";
import NavBar from "~/Components/NavBar";
import SideBar from "~/Components/SideBar";
import ProjectCreator from "~/Components/ProjectCreator";
import { useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import React from "react";
import EditProjects from "~/Components/EditProjects";
import HamburgerMenu from "~/Components/HambugerMenu";

interface PublicMetadata {
  [key: string]: boolean;
}

interface User {
  publicMetadata?: PublicMetadata;
}

const Home: NextPage = () => {
  const { user } = useUser() as { user?: User };
  const { data: users } = api.users.getAll.useQuery();

  if (!users) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>TimeIt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          templateAreas={{
            base: `"nav nav" 
                   "hamburger main"`,
            lg: `"nav nav" 
                 "aside main"`,
          }}
          templateColumns={{ base: "1fr", lg: "200px 1fr" }}
        >
          <GridItem area="nav">
            <NavBar />
          </GridItem>
          <Show above="lg">
            <GridItem area="aside">
              <SideBar />
            </GridItem>
          </Show>
          <Show below="lg">
            <GridItem area="hamburger">
              <HamburgerMenu />
            </GridItem>
          </Show>
          <GridItem area="main">
            {user?.publicMetadata?.["isProjectLeader"] && (
              <Box w={[430, 800, 1300]} pl={2}>
                <Accordion>
                  <ProjectCreator users={users} />
                  <EditProjects />
                </Accordion>
              </Box>
            )}
          </GridItem>
        </Grid>
      </main>
    </>
  );
};

export default Home;
