import { type NextPage } from "next";
import Head from "next/head";

import { Grid, GridItem, Show } from "@chakra-ui/react";
import NavBar from "~/Components/NavBar";
import SideBar from "~/Components/SideBar";
import UsersList from "~/Components/UsersList";
import { useUser } from "@clerk/nextjs";
import HamburgerMenu from "~/Components/HambugerMenu";
import React from "react";

interface PublicMetadata {
  [key: string]: boolean;
}

interface User {
  publicMetadata?: PublicMetadata;
}

const Home: NextPage = () => {
  const { user } = useUser() as { user?: User };
  if (!user?.publicMetadata?.["isProjectLeader"]) {
    return <div>You are not authorized to access this page</div>;
  }

  return (
    <>
      <Head>
        <title>TimeIt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          templateAreas={{
            base: `"nav nav" 
                   "hamburger main"`,
            lg: `"nav nav" 
                 "aside main"`,
          }}
          templateColumns={{ base: "1fr", lg: "200px 1fr" }}
        >
          <GridItem area="nav">
            <NavBar />
          </GridItem>
          <Show above="lg">
            <GridItem area="aside">
              <SideBar />
            </GridItem>
          </Show>
          <Show below="lg">
            <GridItem area="hamburger">
              <HamburgerMenu />
            </GridItem>
          </Show>
          <GridItem area="main">
            {user?.publicMetadata?.["isAdmin"] && <UsersList />}
          </GridItem>
        </Grid>
      </main>
    </>
  );
};

export default Home;
