import React, { useMemo, useState } from "react";
import Head from "next/head";

import {
  Box,
  Button,
  Grid,
  GridItem,
  Input,
  Show,
  Table,
  TableContainer,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
} from "@chakra-ui/react";
import NavBar from "~/Components/NavBar";
import SideBar from "~/Components/SideBar";
import { useUser } from "@clerk/nextjs";
import { api, RouterOutputs } from "~/utils/api";

const dateOffset = (date: Date, offset: number) => {
  const newDate = new Date(date);
  newDate.setDate(date.getDate() + offset);
  return newDate;
};

const getFirstDayOfWeek = (date: Date) => {
  const day = (date.getDay() + 6) % 7; // Monday is the first day of week
  return dateOffset(date, -day);
};

const weekDayFormat = { weekday: "short", month: "short", day: "numeric" };

interface Data {
  project: string;
  time_entries: object;
}

type projectData = Data[];

interface TimeEntry {
  [key: string]: number;
}

const Timesheet = () => {
  const user = useUser();

  const { data } = api.test.getAll.useQuery();

  console.log(JSON.stringify(data));

  type ProjectWithUser = RouterOutputs["test"]["getAll"][number];

  const formattedData = data?.map(({ project }) => {
    const { project: projectName, time_entries } = project;
    const hoursPerDate = time_entries.reduce((acc, { hours_worked, date }) => {
      const formattedDate = new Date(date).toLocaleDateString("en-SE");
      acc[formattedDate] = (acc[formattedDate] || 0) + hours_worked;
      return acc;
    }, {} as TimeEntry);
    return {
      project,
      time_entries: hoursPerDate,
    };
  });

  console.log(formattedData);

  const [startDate, setStartDate] = useState(getFirstDayOfWeek(new Date()));
  const isFutureStartDate = useMemo(() => startDate > new Date(), [startDate]);
  const [timeData, setTimeData] = useState<projectData>([
    { project: "Project 1", time_entries: {} },
  ]);

  const handlePreviousWeek = () => {
    setStartDate((currDate) => dateOffset(currDate, -7));
  };

  const handleNextWeek = () => {
    setStartDate((currDate) => dateOffset(currDate, 7));
  };

  const getValue = (index: number, date: Date) => {
    const key = date.toLocaleDateString("en-SE");
    return formattedData?.[index]?.time_entries?.[key] ?? "";
  };

  const setValue = (index: number, date: Date, value: string) => {
    const key = date.toLocaleDateString("en-SE");
    setTimeData((prevData) => {
      const newData = [...prevData];
      if (value === "")
        delete newData[index].time_entries[key]; // remove key if empty
      else newData[index].time_entries[key] = value;
      return newData;
    });
  };

  const handleAddRow = () => {
    setTimeData([
      ...timeData,
      {
        project: `Project ${timeData.length + 1}`,
        time_entries: {},
      },
    ]);
  };

  const handleDeleteRow = (index: number) => {
    setTimeData((prevData) => {
      const updatedData = [...prevData];
      updatedData.splice(index, 1);
      return updatedData;
    });
  };

  const getTotal = (index: number, dates: []) => {
    return dates.reduce((total, date) => {
      const val = 1 * getValue(index, date);
      return total + val;
    }, 0);
  };

  const weekDates = Array.from({ length: 7 }, (_, i) =>
    dateOffset(startDate, i)
  );

  return (
    <>
      <Head>
        <title>TimeIt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          templateAreas={{
            base: `"nav" 
                   "main"`,
            lg: `"nav nav" 
                 "aside main"`,
          }}
          templateColumns={{ base: "1fr", lg: "200px 1fr" }}
        >
          <GridItem area="nav">
            <NavBar />
          </GridItem>
          <Show above="lg">
            <GridItem area="aside">
              <SideBar />
            </GridItem>
          </Show>
          {!!user.isSignedIn && (
            <GridItem area="main">
              <Box paddingLeft={2}>
                <Button onClick={handlePreviousWeek}>Previous Week</Button>
                {` ${weekDates[0].toLocaleDateString(
                  "en-SE"
                )} - ${weekDates[6].toLocaleDateString("en-SE")} `}
                <Button onClick={handleNextWeek}>Next Week</Button>
                <TableContainer>
                  <Table>
                    <Thead>
                      <Tr>
                        <Th>Project</Th>
                        {weekDates.map((day) => (
                          <Th key={day}>
                            {day.toLocaleDateString("en-SE", weekDayFormat)}
                          </Th>
                        ))}
                        <Th>Total</Th>
                      </Tr>
                    </Thead>
                    <Tbody>
                      {timeData.map((item, index) => (
                        <Tr key={index}>
                          <Td>{item.project}</Td>
                          {weekDates.map((date) => (
                            <Td key={date}>
                              <Input
                                size="sm"
                                type="number"
                                value={getValue(index, date)}
                                onChange={(e) =>
                                  setValue(index, date, e.target.value)
                                }
                                disabled={isFutureStartDate}
                              />
                            </Td>
                          ))}
                          <Td>{getTotal(index, weekDates)}</Td>
                          <Td>
                            <Button onClick={() => handleDeleteRow(index)}>
                              Delete
                            </Button>
                          </Td>
                        </Tr>
                      ))}
                      <Tr>
                        <Td></Td>
                        {weekDates.map((day) => (
                          <Th key={day}>
                            {day.toLocaleDateString("en-SE", weekDayFormat)}
                          </Th>
                        ))}
                      </Tr>
                    </Tbody>
                  </Table>
                </TableContainer>
                <button onClick={handleAddRow}>Add New Project</button>
              </Box>
            </GridItem>
          )}
          {!user.isSignedIn && <h1>You must sign in</h1>}
        </Grid>
      </main>
    </>
  );
};

export default Timesheet;
